config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  
  # exhibitions
  get "/exhibitions" => "exhibitions#index"
  get "/exhibitions/new" => "exhibitions#new"
  
  # museums
  resources :museums, except: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
  belongs_to :museum
end

app/models/museum.rb
class Museum < ApplicationRecord
  # Properties
  # t.references :prefecture, null: false, foreign_key: true
  # t.string :name
  # t.string :address
  # t.time :opening_at
  # t.time :closing_at
  # t.integer :closed_day
  #
  # t.timestamps
  
  # Relations
  has_many :exhibitions
  belongs_to :prefecture
  
  enum closed_day: {
    sunday:    0,
    monday:    1,
    tuesday:   2,
    wednesday: 3,
    tursday:   4,
    friday:    5,
    saturday:  6
  }
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  belongs_to :region
end

app/models/region.rb
class Region < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
  
  def index
    @museums = Museum.all.map do |museum|
      {
        "name":        museum.name,
        "address":     museum.address,
        "exhibitions": museum.exhibitions.all.map { |e| e.title },
      }
    end
  end

end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  def show
    @museum = Museum.find(params[:id])
  end
  
  def new
    @museum     = Museum.new
    @prefecture = Prefecture.all
  end
  
  def create
    @museum = Museum.new(
      name:       museum_params[:name],
      address:    museum_params[:address],
      opening_at: museum_params[:opening_at],
      closing_at: museum_params[:closing_at],
      closed_day: museum_params[:closed_day].to_i,
      prefecture: Prefecture.find(museum_params[:prefecture_id])
    )
    
    if @museum.save
      redirect_to @museum
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @museum     = Museum.find(params[:id])
    @prefecture = Prefecture.all
  end
  
  def update
    @museum = Museum.find(params[:id])
    
    if @museum.update(
      name:       museum_params[:name],
      address:    museum_params[:address],
      opening_at: museum_params[:opening_at],
      closing_at: museum_params[:closing_at],
      closed_day: museum_params[:closed_day].to_i,
      prefecture: Prefecture.find(museum_params[:prefecture_id])
    )
      redirect_to @museum
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    Museum.find(params[:id]).destroy
    redirect_to root_path, status: :see_other
  end
  
  private def museum_params
    params.require(:museum).permit(:name, :address, :opening_at, :closing_at, :closed_day, :prefecture_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/views/exhibitions/index.html.slim
link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/frappe-gantt/0.5.0/frappe-gantt.css"
script src="https://cdnjs.cloudflare.com/ajax/libs/frappe-gantt/0.5.0/frappe-gantt.min.js"
= @museums

.gantt-wrap
  svg#gantt


javascript:
    const tasks = [
        {
            id: 'id1',
            name: '確定申告する',
            description: '必ずやる!!',
            start: '2021-01-01',
            end: '2021-01-7',
            progress: 100,
        },
        {
            id: 'id2',
            name: 'クライアントに挨拶',
            description: '年賀状も確認した上で連絡する',
            start: '2021-01-4',
            end: '2021-01-8',
            progress: 100,
        },
        {
            id: 'id3',
            name: '請求書作成',
            description: 'みんなに稼働時間を記録してもらった上で請求を出す',
            start: '2021-01-5',
            end: '2021-01-6',
            progress: 40,
        },
        {
            id: 'id4',
            name: '案件A を開発',
            description: 'まずはフレームワークのアップデートやる!',
            start: '2021-01-5',
            end: '2021-01-11',
            progress: 50,
        },
        {
            id: 'id5',
            name: 'フィードバック面談',
            description: '各メンバーシートを記入してもらった上で 1on1',
            start: '2021-01-12',
            end: '2021-01-16',
            progress: 20,
        },
    ];

    const gantt = new Gantt("#gantt", tasks, {
        // ダブルクリック時
        on_click: (task) => {
            console.log(task.description);
        }
    });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exhibition</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_importmap_tags %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/museums/edit.html.slim
h1 Edit Museum

= form_with model: @museum do |form|
  div
    = form.label :name
    br
    = form.text_field :name
  div
    = form.label :address
    br
    = form.text_area :address
  div
    = form.time_field :opening_at
  div
    = form.time_field :closing_at
  div
    = form.weekday_select :closed_day, index_as_value: true
  div
    = form.select :prefecture_id, @prefecture.map {|p| [p.name, p.id]}, { include_blank: '選択してください' }
  div
    = form.submit

app/views/museums/new.html.slim
h1 New Museum

= form_with model: @museum do |form|
  div
    = form.label :name
    br
    = form.text_field :name
  div
    = form.label :address
    br
    = form.text_area :address
  div
    = form.time_field :opening_at
  div
    = form.time_field :closing_at
  div
    = form.weekday_select :closed_day, index_as_value: true
  div
    = form.select :prefecture_id, @prefecture.map {|p| [p.name, p.id]}, { include_blank: '選択してください' }
  div
    = form.submit

app/views/museums/show.html.slim
h1
  = @museum.name
div
  = @museum.address
div
  = @museum.prefecture.name
div
  = @museum.opening_at
  = @museum.closing_at
div
  = @museum.closed_day
ul
  li
    = link_to "Edit", edit_museum_path(@museum)
  li
    = link_to "Delete", museum_path(@museum), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }

h2 展覧会
ul
  - @museum.exhibitions.each do |exhibition|
    li
      = exhibition.title
      = exhibition.start_date
      = exhibition.end_date
      = exhibition.price